/**
 * Verifies a Cloudflare Turnstile CAPTCHA token against the Cloudflare siteverify API.
 *
 * @param token - The one-time token generated by the Turnstile widget on the client side.
 * @returns A promise resolving to true if the token is valid, false otherwise.
 */
export async function verifyTurnstileToken(token: string): Promise<boolean> {
  const secret = process.env.TURNSTILE_SECRET_KEY

  if (!secret) {
    // eslint-disable-next-line no-console
    console.error(
      '[Turnstile] TURNSTILE_SECRET_KEY is missing from environment variables. Verification will fail automatically.',
    )
    return false
  }

  const controller = new AbortController()
  const timeoutId = setTimeout(() => controller.abort(), 5000)

  try {
    const res = await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: `secret=${encodeURIComponent(secret)}&response=${encodeURIComponent(token)}`,
      signal: controller.signal,
    })
    const data = await res.json()
    return data.success === true
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('[Turnstile] Verification request failed:', err)
    return false
  } finally {
    clearTimeout(timeoutId)
  }
}
